Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Online_Exam_System.Data;

namespace Online_Exam_System.Controllers.Admin
{
    public class AdminController : Controller
    {
        // GET: Admin/Index
        
        public IActionResult Index()
        {
            return View("~/Views/Admin/Index.cshtml");
        }
        
       
    }
}

Controllers/Admin/CssController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Online_Exam_System.Data;
using Online_Exam_System.Models.Admin;

namespace Online_Exam_System.Controllers.Admin
{
    public class CssController : Controller
    {
        private readonly dbContext _context;

        public CssController(dbContext context)
        {
            _context = context;
        }

        // GET: Css
        public async Task<IActionResult> Index()
        {
            return View("~/Views/Admin/Css/Index.cshtml", await _context.Css.ToListAsync());
        }

        public async Task<IActionResult> CssExamination()
        {
            var data = await _context.Css.ToListAsync();

            //create a random renerate values with random object

            return View("~/Views/CssExam/CssExamination.cshtml", data);
        }

        public IActionResult CssResult()
        {
            var data = _context.Css.ToList();
            return View("~/Views/Css/CssResult.cshtml", data);
        }

        // GET: Css/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var css = await _context.Css
                .FirstOrDefaultAsync(m => m.Id == id);
            if (css == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/Css/Details.cshtml",css);
        }

        // GET: Css/Create
        public IActionResult Create()
        {
            return View("~/Views/Admin/Css/Create.cshtml");
        }

        // POST: Css/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Question,CorrectAnswer,Ans1,Ans2,Ans3")] Css css)
        {
            if (ModelState.IsValid)
            {
                _context.Add(css);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Admin/Css/Create.cshtml",css);
        }

        // GET: Css/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var css = await _context.Css.FindAsync(id);
            if (css == null)
            {
                return NotFound();
            }
            return View("~/Views/Admin/Css/Edit.cshtml",css);
        }

        // POST: Css/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,CorrectAnswer,Ans1,Ans2,Ans3")] Css css)
        {
            if (id != css.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(css);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CssExists(css.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Admin/Css/Edit.cshtml",css);
        }

        // GET: Css/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var css = await _context.Css
                .FirstOrDefaultAsync(m => m.Id == id);
            if (css == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/Css/Delete.cshtml",css);
        }

        // POST: Css/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var css = await _context.Css.FindAsync(id);
            _context.Css.Remove(css);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CssExists(int id)
        {
            return _context.Css.Any(e => e.Id == id);
        }
    }
}

Controllers/Admin/HtmlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Online_Exam_System.Data;
using Online_Exam_System.Models.Admin.Html;

namespace Online_Exam_System.Controllers.Admin
{
    public class HtmlController : Controller
    {
        private readonly dbContext _context;

        public HtmlController(dbContext context)
        {
            _context = context;
        }

        // GET: Admin/Html
        public async Task<IActionResult> Index()
        {
            var data = await _context.Html.ToListAsync();
            return View("~/Views/Admin/Html/Index.cshtml",data);
            /*return View(await _context.Html.ToListAsync());*/
        }

       
        public async Task<IActionResult> HtmlExamimation()
        {
            var data = await _context.Html.ToListAsync();

            //create a random renerate values with random object

            return View("~/Views/HtmlExam/HtmlExamimation.cshtml",data);
        }

        public IActionResult HtmlResult()
        {
            var data = _context.Html.ToList();
            return View("~/Views/Html/HtmlResult.cshtml", data);
        }

        // GET: Admin/Html/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var html = await _context.Html
                .FirstOrDefaultAsync(m => m.Id == id);
            if (html == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/Html/Details.cshtml",html);
        }

        // GET: Admin/Html/Create
        public IActionResult Create()
        {
            return View("~/Views/Admin/Html/Create.cshtml");
        }

        // POST: Admin/Html/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Question,CorrectAnswer,Ans1,Ans2,Ans3")] Html html)
        {
            if (ModelState.IsValid)
            {
                _context.Add(html);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Admin/Html/Create.cshtml",html);
        }

        // GET: Admin/Html/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var html = await _context.Html.FindAsync(id);
            if (html == null)
            {
                return NotFound();
            }
            return View("~/Views/Admin/Html/Edit.cshtml",html);
        }

        // POST: Admin/Html/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,CorrectAnswer,Ans1,Ans2,Ans3")] Html html)
        {
            if (id != html.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(html);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HtmlExists(html.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Admin/Html/Edit.cshtml",html);
        }

        // GET: Admin/Html/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var html = await _context.Html
                .FirstOrDefaultAsync(m => m.Id == id);
            if (html == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/Html/Delete.cshtml",html);
        }

        // POST: Admin/Html/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var html = await _context.Html.FindAsync(id);
            _context.Html.Remove(html);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HtmlExists(int id)
        {
            return _context.Html.Any(e => e.Id == id);
        }
    }
}

Controllers/Admin/PhpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Online_Exam_System.Data;
using Online_Exam_System.Models.Admin;

namespace Online_Exam_System.Controllers.Admin
{
    public class PhpController : Controller
    {
        private readonly dbContext _context;

        public PhpController(dbContext context)
        {
            _context = context;
        }

        // GET: Php
        public async Task<IActionResult> Index()
        {
            return View("~/Views/Admin/Php/Index.cshtml",await _context.Php.ToListAsync());
        }

        public async Task<IActionResult> PhpExamination()
        {
            var data = await _context.Php.ToListAsync();

            //create a random renerate values with random object

            return View("~/Views/PhpExam/PhpExamination.cshtml", data);
        }

        public IActionResult PhpResult()
        {
            var data = _context.Php.ToList();
            return View("~/Views/Php/PhpResult.cshtml", data);
        }

        // GET: Php/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var php = await _context.Php
                .FirstOrDefaultAsync(m => m.Id == id);
            if (php == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/Php/Details.cshtml",php);
        }

        // GET: Php/Create
        public IActionResult Create()
        {
            return View("~/Views/Admin/Php/Create.cshtml");
        }

        // POST: Php/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Question,CorrectAnswer,Ans1,Ans2,Ans3")] Php php)
        {
            if (ModelState.IsValid)
            {
                _context.Add(php);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Admin/Php/Create.cshtml",php);
        }

        // GET: Php/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var php = await _context.Php.FindAsync(id);
            if (php == null)
            {
                return NotFound();
            }
            return View("~/Views/Admin/Php/Edit.cshtml",php);
        }

        // POST: Php/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,CorrectAnswer,Ans1,Ans2,Ans3")] Php php)
        {
            if (id != php.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(php);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhpExists(php.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Admin/Php/Edit.cshtml",php);
        }

        // GET: Php/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var php = await _context.Php
                .FirstOrDefaultAsync(m => m.Id == id);
            if (php == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/Php/Delete.cshtml",php);
        }

        // POST: Php/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var php = await _context.Php.FindAsync(id);
            _context.Php.Remove(php);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhpExists(int id)
        {
            return _context.Php.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager 
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - Learn &mdash; Free Website Template, Free HTML5 Template by freehtml5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
    <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="freehtml5.co" />

    <!--
    //////////////////////////////////////////////////////

    FREE HTML5 TEMPLATE
    DESIGNED & DEVELOPED by FreeHTML5.co

    Website: 		http://freehtml5.co/
    Email: 			info@freehtml5.co
    Twitter: 		http://twitter.com/fh5co
    Facebook: 		https://www.facebook.com/fh5co

    //////////////////////////////////////////////////////
     -->
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/css/style.css">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />*@

    <!-- Modernizr JS -->
    <script src="~/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <div class="fh5co-loader"></div>

    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="top">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            <p class="num">Call: +01 123 456 7890</p>
                            <ul class="fh5co-social">
                                <li><a href="https://twitter.com/facebook"><i class="icon-twitter"></i></a></li>
                                <li><a href="https://www.facebook.com/"><i class="icon-facebook"></i></a></li>
                                <li><a href="https://www.linkedin.com/"><i class="icon-linkedin"></i></a></li>
                                <li><a href="https://www.youtube.com/"><i class="icon-youtube"></i></a></li>
                                <li><a asp-area="" asp-controller="Admin" asp-action="Index"><i class="icon-aircraft">Admin</i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="top-menu">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-1">
                            <div id="fh5co-logo"><a asp-area="" asp-controller="Home" asp-action="Index">Exampedia<span>.</span></a></div>
                        </div>
                        <div class="col-xs-11 text-right menu-1">
                            <ul>
                                <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                                <li class="has-dropdown">
                                    <a asp-area="" asp-controller="Home" asp-action="Exam">Exam</a>
                                    <ul class="dropdown">
                                        <li><a asp-area="" asp-controller="Html" asp-action="HtmlExamimation">HTML</a></li>
                                        <li><a asp-area="" asp-controller="Css" asp-action="CssExamination">CSS</a></li>
                                        <li><a asp-area="" asp-controller="Javascript" asp-action="JavascriptExamination">JavaScript</a></li>
                                        <li><a asp-area="" asp-controller="Php" asp-action="PhpExamination">PHP</a></li>
                                    </ul>
                                </li>
                                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                                <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                                @if (signInManager.IsSignedIn(User))
                                {
                                <li class="btn-cta">
                                    <form method="post" asp-action="Logout" asp-controller="Home">
                                        <button type="submit" ><span>Logout</span></button>
                                    </form>
                                </li>
                                }
                                else
                                {
                                    <li class="btn-cta"><a asp-area="" asp-controller="Home" asp-action="Login"><span>Login</span></a></li>
                                    <li class="btn-cta"><a asp-area="" asp-controller="Home" asp-action="Register"><span>Register</span></a></li>
                                }

                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </nav>




        @RenderBody()


        <footer id="fh5co-footer" role="contentinfo">
            <div class="container">
                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">&copy; 2020 Exampedia. All Rights Reserved.</small>
                            <small class="block">Designed by <a href="http://soniaverma.ca/" target="_blank">Sonia Verma</a> </small>
                        </p>
                        <p>
                            <ul class="fh5co-social-icons">
                                <li><a href="https://twitter.com/facebook"><i class="icon-twitter"></i></a></li>
                                <li><a href="https://www.facebook.com/"><i class="icon-facebook"></i></a></li>
                                <li><a href="https://www.linkedin.com/"><i class="icon-linkedin"></i></a></li>
                                <li><a href="https://www.youtube.com/"><i class="icon-youtube"></i></a></li>
                            </ul>
                        </p>
                    </div>
                </div>

            </div>
        </footer>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!-- jQuery -->
    <script src="~/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/js/jquery.waypoints.min.js"></script>
    <!-- Stellar Parallax -->
    <script src="~/js/jquery.stellar.min.js"></script>
    <!-- Carousel -->
    <script src="~/js/owl.carousel.min.js"></script>
    <!-- countTo -->
    <script src="~/js/jquery.countTo.js"></script>
    <!-- Magnific Popup -->
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/magnific-popup-options.js"></script>
    <!-- Main -->

    <script src="~/js/main.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Panel</title>
    <link rel="stylesheet" href="~/Admin/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Admin/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="padding-left: 50px; padding-right:25px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item" style="padding-left: 25px; padding-right:25px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Html" asp-action="index">Html</a>
                        </li>
                        <li class="nav-item" style="padding-left: 25px; padding-right:25px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Css" asp-action="index">Css</a>
                        </li>
                        <li class="nav-item" style="padding-left: 25px; padding-right:25px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Javascript" asp-action="index">Javascript</a>
                        </li>
                        <li class="nav-item" style="padding-left: 25px; padding-right:25px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Php" asp-action="index">Php</a>
                        </li>
                        <li class="nav-item" style="padding-left: 25px; ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="index">Back To Website</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Online Exam Sysyem - Admin Panel
        </div>
    </footer>
    <script src="~/Admin/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Admin/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Admin/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>